apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - api.yaml
  - loki.yaml
  - grafana.yaml
  - alloy.yaml
  - gateway.yaml
  - k6-job.yaml
