[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*-json.log
    Parser            docker
    Tag               docker.*
    Mem_Buf_Limit     10MB
    Skip_Long_Lines   On
    Refresh_Interval  2

[FILTER]
    Name              parser
    Match             docker.*
    Key_Name          log
    Parser            api_json
    Preserve_Key      Off
    Reserve_Data      On

[FILTER]
    Name              grep
    Match             docker.*
    Regex             service ^api-vet$

[FILTER]
    Name              modify
    Match             docker.*
    Add               container api-vet
    Add               environment dev

[OUTPUT]
    Name              loki
    Match             docker.*
    Host              loki
    Port              3100
    Labels            job=fluent-bit,service=api-vet,container=api-vet,environment=dev
    Line_Format       json
    Auto_Kubernetes_Labels Off

