namespace: observability
api:
  image:
    repository: api-vet
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 2
  service:
    port: 8000

loki:
  image:
    repository: grafana/loki
    tag: 2.9.3
  persistence:
    size: 10Gi

alloy:
  image:
    repository: grafana/alloy
    tag: latest

grafana:
  image:
    repository: grafana/grafana
    tag: 10.4.2
  adminUser: admin
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30030

gateway:
  host: api.local
  className: traefik
