services:
  api:
    build: .
    container_name: api-vet-alloy
    ports:
      - "8000:8000"
    networks: [observability]

  alloy:
    image: grafana/alloy:latest
    container_name: alloy-api-vet
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
    volumes:
      - ../../config-files/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - alloy-data:/var/lib/alloy/data
    depends_on: [api, loki]
    networks: [observability]

  loki:
    image: grafana/loki:2.9.3
    container_name: loki-api-vet-alloy
    command: -config.file=/etc/loki/config.yml
    ports:
      - "3100:3100"
    volumes:
      - ../../config-files/loki/loki-config.yml:/etc/loki/config.yml:ro
      - loki-alloy-data:/loki
    networks: [observability]

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana-api-vet-alloy
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_BASIC_ENABLED: "false"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/dashboards/api-vet-loki.json
    volumes:
      - ../../config-files/grafana/provisioning:/etc/grafana/provisioning:ro
      - ../../config-files/grafana/dashboards:/etc/grafana/dashboards:ro
      - grafana-alloy-data:/var/lib/grafana
    depends_on: [loki]
    networks: [observability]

volumes:
  alloy-data:
  loki-alloy-data:
  grafana-alloy-data:

networks:
  observability:

