services:
  api:
    build: .
    container_name: api-vet-fluent-bit
    ports:
      - "8000:8000"
    networks: [observability]

  fluent-bit:
    image: fluent/fluent-bit:3.2
    container_name: fluent-bit-api-vet
    volumes:
      - ../../config-files/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ../../config-files/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on: [api, loki]
    networks: [observability]

  loki:
    image: grafana/loki:2.9.3
    container_name: loki-api-vet-fluent-bit
    command: -config.file=/etc/loki/config.yml
    ports:
      - "3100:3100"
    volumes:
      - ../../config-files/loki/loki-config.yml:/etc/loki/config.yml:ro
      - loki-fluent-bit-data:/loki
    networks: [observability]

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana-api-vet-fluent-bit
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_BASIC_ENABLED: "false"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/dashboards/api-vet-loki.json
    volumes:
      - ../../config-files/grafana/provisioning:/etc/grafana/provisioning:ro
      - ../../config-files/grafana/dashboards:/etc/grafana/dashboards:ro
      - grafana-fluent-bit-data:/var/lib/grafana
    depends_on: [loki]
    networks: [observability]

volumes:
  loki-fluent-bit-data:
  grafana-fluent-bit-data:

networks:
  observability:
